// Flock names pool for the game
// First name is always the player, rest are for enemy flocks

export const FLOCK_NAMES = [
    "You",              // Player
    "Crimson Tide",
    "Shadow Legion",
    "Venom Swarm",
    "Frost Fangs",
    "Thunder Hawks",
    "Ember Wolves",
    "Void Hunters",
    "Storm Riders",
    "Iron Talons",
    "Night Crawlers",
    "Blaze Runners",
    "Phantom Flock",
    "Apex Predators",
    "Omega Squad",
    "Neon Vipers",
    "Chaos Swarm",
    "Glacier Pack",
    "Solar Flares",
    "Dark Matter",
    "Cyber Sharks",
    "Plasma Horde",
    "Nebula Swarm",
    "Toxic Wasps",
    "Crystal Claws",
    "Obsidian Wings",
    "Quantum Drift",
    "Savage Pulse",
    "Binary Flock",
    "Magma Core",
    "Azure Storm",
    "Primal Fury",
    "Static Surge",
    "Lunar Eclipse",
    "Inferno Clan",
    "Turbo Swarm",
    "Vortex Squad",
    "Crimson Dawn",
    "Arctic Blitz",
    "Nova Burst"
];
